// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FindTeacherClient is the client API for FindTeacher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindTeacherClient interface {
	SayTeacher(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Teacher, error)
}

type findTeacherClient struct {
	cc grpc.ClientConnInterface
}

func NewFindTeacherClient(cc grpc.ClientConnInterface) FindTeacherClient {
	return &findTeacherClient{cc}
}

func (c *findTeacherClient) SayTeacher(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Teacher, error) {
	out := new(Teacher)
	err := c.cc.Invoke(ctx, "/pb.findTeacher/sayTeacher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindTeacherServer is the server API for FindTeacher service.
// All implementations must embed UnimplementedFindTeacherServer
// for forward compatibility
type FindTeacherServer interface {
	SayTeacher(context.Context, *Student) (*Teacher, error)
	mustEmbedUnimplementedFindTeacherServer()
}

// UnimplementedFindTeacherServer must be embedded to have forward compatible implementations.
type UnimplementedFindTeacherServer struct {
}

func (UnimplementedFindTeacherServer) SayTeacher(context.Context, *Student) (*Teacher, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayTeacher not implemented")
}
func (UnimplementedFindTeacherServer) mustEmbedUnimplementedFindTeacherServer() {}

// UnsafeFindTeacherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindTeacherServer will
// result in compilation errors.
type UnsafeFindTeacherServer interface {
	mustEmbedUnimplementedFindTeacherServer()
}

func RegisterFindTeacherServer(s grpc.ServiceRegistrar, srv FindTeacherServer) {
	s.RegisterService(&FindTeacher_ServiceDesc, srv)
}

func _FindTeacher_SayTeacher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindTeacherServer).SayTeacher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.findTeacher/sayTeacher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindTeacherServer).SayTeacher(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

// FindTeacher_ServiceDesc is the grpc.ServiceDesc for FindTeacher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindTeacher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.findTeacher",
	HandlerType: (*FindTeacherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sayTeacher",
			Handler:    _FindTeacher_SayTeacher_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
